function run() {
    print("for(i = 0; i < 4; i++;){");
    moveForward();
    turnRight();
    moveForward();
    turnLeft();
    print("};");
    print("i == 1");
    moveForward();
    turnRight();
    moveForward();
    turnLeft();
    print("i == 2");
    moveForward();
    turnRight();
    moveForward();
    turnLeft();
    print("i == 3");
    moveForward();
    turnRight();
    moveForward();
    turnLeft();
    print("i == 4");
    print("exit loop");
    moveForward();
    moveForward();
};